---
title: "First steps in Data Science - Part 1"
subtitle: "Does money make people happier?"
author: "Prof. Dr. Jan Kirenz, HdM Stuttgart"
output:
 html_document:
  code_download: true
  fig_height: 4
  fig_width: 4
  highlight: tango
  number_sections: yes
  toc: yes
  toc_depth: 3
  toc_float: 
    collapsed: false
    smooth_scroll: true 
  theme: paper
  df_print: paged
---


```{css, echo=FALSE}

/* css code to change the look of the HTML-output */
  
h1 {
  color: #D0313C;
  font-size: 200%;
  }
h2 {
  color: #D0313C;
  font-size: 150%;
  }
h3 {
  font-size: 120%;
  font-weight: bold;
  }
h4 {
  color: rgb(139, 142, 150);
  font-size: 100%;
  font-weight: bold;
  }

```


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```


# Setup

```{r}

# Load packages
library(tidyverse) # collection of important data science packages
library(tidymodels)  # collection of packages for modeling and ml
library(janitor) # data preparation package
library(kknn) # K-nearest neighbor model

```

# Data import

```{r}

# Import the data from GitHub
LINK = "https://raw.githubusercontent.com/kirenz/datasets/master/oecd_gdp.csv"
df <- read_csv(LINK)

# Take a look at the data
glimpse(df)

```

# Data preparation

```{r fig.width=4, fig.height=4}

# Change column names
df <-  clean_names(df)

# Visualize the data
ggplot(df, aes(x=gdp_per_capita, 
               y=life_satisfaction)) +
  geom_point() +
  theme_classic()

```


# Model selection

Linear regression model:

```{r}

lm_mod <- 
  linear_reg() %>% 
  set_engine("lm") %>% 
  set_mode(mode = "regression") 

```

# Model training 

```{r}

lm_fit <- 
  lm_mod %>% 
  fit(life_satisfaction ~ gdp_per_capita, 
                data = df)

```

Model summary:

```{r}

tidy(lm_fit)

```

# Model prediction

```{r}

lm_pred <-
  lm_fit %>%
  predict(new_data = df) %>%
  mutate(y_truth = df$life_satisfaction)

head(lm_pred)

```

Alternatively, we could use `augment()` to obtain model predictions as well es residuals:

```{r}
lm_pred_aug <- augment(lm_fit$fit, data = df)

head(lm_pred_aug)

```


# Model evaluation

Root mean squared error:

```{r}

rmse(truth = y_truth, # true values
     estimate = .pred,  # model predictions
     lm_pred) # data

```

More performance measures:

```{r}

glance(lm_fit$fit) 

```

Make a prediction for a new GDP value:

```{r}

# New GDP per capita
X_new <-  tibble(gdp_per_capita = c(50000)) 

# Predict and print output
(predict(lm_fit, new_data = X_new))

```

# Alternative model

K-nearest neighbor:

```{r}

# Model selection
knn_mod <- 
  nearest_neighbor(neighbors = 3) %>% 
  set_engine("kknn") %>% 
  set_mode("regression") 

# Model training
knn_fit <- 
  knn_mod %>% 
  fit(life_satisfaction ~ gdp_per_capita, 
                data = df)

# Model prediction
knn_pred <-
  knn_fit %>%
  predict(new_data = df) %>%
  mutate(y_truth = df$life_satisfaction)

# Model evaluation
rmse(truth = y_truth, # true values
     estimate = .pred,  # model predictions
     knn_pred) # data

# Predict and print output
(predict(knn_fit, new_data = X_new))

```
