---
title: "First steps in Data Science"
subtitle: "Does money make people happier?"
author: "Prof. Dr. Jan Kirenz, HdM Stuttgart"
output:
 html_document:
  code_download: true
  fig_height: 4
  fig_width: 4
  highlight: tango
  number_sections: yes
  toc: yes
  toc_depth: 3
  toc_float: 
    collapsed: false
    smooth_scroll: true 
  theme: paper
  df_print: paged
---


```{css, echo=FALSE}

/* css code to change the look of the HTML-output */
  
h1 {
  color: #D0313C;
  font-size: 200%;
  }

h2 {
  color: #D0313C;
  font-size: 150%;
  }

h3 {
  font-size: 120%;
  font-weight: bold;
  }

h4 {
  color: rgb(139, 142, 150);
  font-size: 100%;
  font-weight: bold;
  }

```



```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```


# Setup

```{r}

# Common packages
library(tidyverse) # collection of important packages
library(tidymodels)  # collection of data science packages
library(janitor) # data preparation package
library(kknn) # K-nearest neighbor model

```

# Data import

```{r}

# Load the data from GitHub
LINK = "https://raw.githubusercontent.com/kirenz/datasets/master/oecd_gdp.csv"
df <- read_csv(LINK)

# Take a look at the data
glimpse(df)

```

# Data preparation

```{r fig.width=4, fig.height=4}

# Change column names
df <-  clean_names(df)

# Visualize the data
ggplot(df, aes(x=gdp_per_capita, 
               y=life_satisfaction)) +
  geom_point() +
  theme_classic()

```


# Model selection

## Linear regression model

```{r}

lm_spec <- 
  linear_reg() %>% 
  set_engine("lm") %>% 
  set_mode(mode = "regression") 

```

## K-nearest neighbor

```{r}

knn_spec <- 
  nearest_neighbor(neighbors = 3) %>% 
  set_engine("kknn") %>% 
  set_mode("regression") 

```


# Data splitting

```{r}
set.seed(123)

df_split <- initial_split(df) 
df_train <- training(df_split) 
df_test <- testing(df_split)

```


# Model training 

## K-fold cross-validation

```{r}
set.seed(123)

cv_folds <- vfold_cv(df_train, v = 5)

```

## Linear regression

```{r}

lm_fit <- 
  lm_spec %>% 
  fit_resamples(life_satisfaction ~ gdp_per_capita, 
                resamples = cv_folds)

```

```{r}

# Model summary


lm_fit %>% 
  collect_metrics(summarize = TRUE)

```

```{r}
lm_fit %>% 
  collect_metrics(summarize = FALSE)
```


## K-nearest neighbor

```{r}

knn_fit <- 
  knn_spec %>% 
  fit_resamples(life_satisfaction ~ gdp_per_capita, 
                resamples = cv_folds)

```

```{r}

# Model summary
knn_fit %>% 
  collect_metrics(summarize = FALSE)



```


```{r}
knn_fit %>% 
  collect_metrics(summarize = TRUE)
```


# Model testing

```{r}

# Train best model with all training data
last_lm_fit <- 
  lm_spec %>% 
  fit(life_satisfaction ~ gdp_per_capita, 
                data = df_train)

```


```{r}

# Model coefficients
tidy(last_lm_fit)

```

```{r}

# Prediction
last_lm_pred <-
  last_lm_fit %>%
  predict(new_data = df_test) %>%
  mutate(y_truth = df_test$life_satisfaction)

```

```{r}

# Performance measures
rmse(truth = y_truth, 
     estimate = .pred, 
     last_lm_pred) 

```


```{r}

glance(last_lm_fit$fit) # more measures

```

```{r}

# Make a prediction for new GDP values
X_new <-  tibble(gdp_per_capita = c(50000, 25000)) # new GDP per capita

```

```{r}

(predict(last_lm_fit, new_data = X_new))

```

